package com.tao.trade.infra.db.mapper;

import com.tao.trade.infra.db.model.CnMarketDaily;
import com.tao.trade.infra.db.model.CnMarketDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnMarketDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    long countByExample(CnMarketDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int deleteByExample(CnMarketDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int insert(CnMarketDaily row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int insertSelective(CnMarketDaily row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    List<CnMarketDaily> selectByExample(CnMarketDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    CnMarketDaily selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int updateByExampleSelective(@Param("row") CnMarketDaily row, @Param("example") CnMarketDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int updateByExample(@Param("row") CnMarketDaily row, @Param("example") CnMarketDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int updateByPrimaryKeySelective(CnMarketDaily row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_market_daily
     *
     * @mbg.generated Sat Mar 04 20:51:53 CST 2023
     */
    int updateByPrimaryKey(CnMarketDaily row);
}