package com.tao.trade.infra.db.mapper;

import com.tao.trade.infra.db.model.CnStockIpo;
import com.tao.trade.infra.db.model.CnStockIpoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnStockIpoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    long countByExample(CnStockIpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int deleteByExample(CnStockIpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int insert(CnStockIpo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int insertSelective(CnStockIpo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    List<CnStockIpo> selectByExample(CnStockIpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    CnStockIpo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int updateByExampleSelective(@Param("row") CnStockIpo row, @Param("example") CnStockIpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int updateByExample(@Param("row") CnStockIpo row, @Param("example") CnStockIpoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int updateByPrimaryKeySelective(CnStockIpo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_ipo
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    int updateByPrimaryKey(CnStockIpo row);
}