package com.tao.trade.infra.db.mapper;

import com.tao.trade.infra.db.model.CnStockInfo;
import com.tao.trade.infra.db.model.CnStockInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnStockInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    long countByExample(CnStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int deleteByExample(CnStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int insert(CnStockInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int insertSelective(CnStockInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    List<CnStockInfo> selectByExample(CnStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    CnStockInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int updateByExampleSelective(@Param("row") CnStockInfo row, @Param("example") CnStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int updateByExample(@Param("row") CnStockInfo row, @Param("example") CnStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int updateByPrimaryKeySelective(CnStockInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_info
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    int updateByPrimaryKey(CnStockInfo row);
}