package com.tao.trade.infra.db.mapper;

import com.tao.trade.infra.db.model.CnStockDailyStat;
import com.tao.trade.infra.db.model.CnStockDailyStatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnStockDailyStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    long countByExample(CnStockDailyStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int deleteByExample(CnStockDailyStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int insert(CnStockDailyStat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int insertSelective(CnStockDailyStat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    List<CnStockDailyStat> selectByExample(CnStockDailyStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    CnStockDailyStat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int updateByExampleSelective(@Param("row") CnStockDailyStat row, @Param("example") CnStockDailyStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int updateByExample(@Param("row") CnStockDailyStat row, @Param("example") CnStockDailyStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int updateByPrimaryKeySelective(CnStockDailyStat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.cn_stock_daily_stat
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    int updateByPrimaryKey(CnStockDailyStat row);
}