package com.tao.trade.infra.db.mapper;

import com.tao.trade.infra.db.model.QuaintFind;
import com.tao.trade.infra.db.model.QuaintFindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuaintFindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    long countByExample(QuaintFindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int deleteByExample(QuaintFindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int insert(QuaintFind row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int insertSelective(QuaintFind row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    List<QuaintFind> selectByExample(QuaintFindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    QuaintFind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int updateByExampleSelective(@Param("row") QuaintFind row, @Param("example") QuaintFindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int updateByExample(@Param("row") QuaintFind row, @Param("example") QuaintFindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int updateByPrimaryKeySelective(QuaintFind row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.quaint_find
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    int updateByPrimaryKey(QuaintFind row);
}