package com.tao.trade.infra.db.mapper;

import com.tao.trade.infra.db.model.SysStatus;
import com.tao.trade.infra.db.model.SysStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    long countByExample(SysStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    int deleteByExample(SysStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    int insert(SysStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    int insertSelective(SysStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    List<SysStatus> selectByExample(SysStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    int updateByExampleSelective(@Param("row") SysStatus row, @Param("example") SysStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sys_status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    int updateByExample(@Param("row") SysStatus row, @Param("example") SysStatusExample example);
}