package com.tao.trade.infra.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class CnMarketDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.id
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.listing
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private Integer listing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.delisting
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private Integer delisting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.up
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private Integer up;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.down
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private Integer down;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.vol
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private BigDecimal vol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.amount
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.profit
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private BigDecimal profit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.shibor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private BigDecimal shibor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.libor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private BigDecimal libor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.hibor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private BigDecimal hibor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_market_daily.trade_date
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    private Date tradeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.id
     *
     * @return the value of public.cn_market_daily.id
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.id
     *
     * @param id the value for public.cn_market_daily.id
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.listing
     *
     * @return the value of public.cn_market_daily.listing
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public Integer getListing() {
        return listing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.listing
     *
     * @param listing the value for public.cn_market_daily.listing
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setListing(Integer listing) {
        this.listing = listing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.delisting
     *
     * @return the value of public.cn_market_daily.delisting
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public Integer getDelisting() {
        return delisting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.delisting
     *
     * @param delisting the value for public.cn_market_daily.delisting
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setDelisting(Integer delisting) {
        this.delisting = delisting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.up
     *
     * @return the value of public.cn_market_daily.up
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public Integer getUp() {
        return up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.up
     *
     * @param up the value for public.cn_market_daily.up
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setUp(Integer up) {
        this.up = up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.down
     *
     * @return the value of public.cn_market_daily.down
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public Integer getDown() {
        return down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.down
     *
     * @param down the value for public.cn_market_daily.down
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setDown(Integer down) {
        this.down = down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.vol
     *
     * @return the value of public.cn_market_daily.vol
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public BigDecimal getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.vol
     *
     * @param vol the value for public.cn_market_daily.vol
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setVol(BigDecimal vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.amount
     *
     * @return the value of public.cn_market_daily.amount
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.amount
     *
     * @param amount the value for public.cn_market_daily.amount
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.profit
     *
     * @return the value of public.cn_market_daily.profit
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.profit
     *
     * @param profit the value for public.cn_market_daily.profit
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.shibor
     *
     * @return the value of public.cn_market_daily.shibor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public BigDecimal getShibor() {
        return shibor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.shibor
     *
     * @param shibor the value for public.cn_market_daily.shibor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setShibor(BigDecimal shibor) {
        this.shibor = shibor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.libor
     *
     * @return the value of public.cn_market_daily.libor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public BigDecimal getLibor() {
        return libor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.libor
     *
     * @param libor the value for public.cn_market_daily.libor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setLibor(BigDecimal libor) {
        this.libor = libor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.hibor
     *
     * @return the value of public.cn_market_daily.hibor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public BigDecimal getHibor() {
        return hibor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.hibor
     *
     * @param hibor the value for public.cn_market_daily.hibor
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setHibor(BigDecimal hibor) {
        this.hibor = hibor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_market_daily.trade_date
     *
     * @return the value of public.cn_market_daily.trade_date
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public Date getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_market_daily.trade_date
     *
     * @param tradeDate the value for public.cn_market_daily.trade_date
     *
     * @mbg.generated Sun Feb 26 11:16:46 CST 2023
     */
    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }
}