package com.tao.trade.infra.db.model;

import java.util.Date;

public class CnStockInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.id
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.status
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.symbol
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.name
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.industry
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.market
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.exchange
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.list_date
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private Date listDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_info.create_date
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.id
     *
     * @return the value of public.cn_stock_info.id
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.id
     *
     * @param id the value for public.cn_stock_info.id
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.status
     *
     * @return the value of public.cn_stock_info.status
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.status
     *
     * @param status the value for public.cn_stock_info.status
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.symbol
     *
     * @return the value of public.cn_stock_info.symbol
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.symbol
     *
     * @param symbol the value for public.cn_stock_info.symbol
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.name
     *
     * @return the value of public.cn_stock_info.name
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.name
     *
     * @param name the value for public.cn_stock_info.name
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.industry
     *
     * @return the value of public.cn_stock_info.industry
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.industry
     *
     * @param industry the value for public.cn_stock_info.industry
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.market
     *
     * @return the value of public.cn_stock_info.market
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.market
     *
     * @param market the value for public.cn_stock_info.market
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setMarket(String market) {
        this.market = market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.exchange
     *
     * @return the value of public.cn_stock_info.exchange
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.exchange
     *
     * @param exchange the value for public.cn_stock_info.exchange
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.list_date
     *
     * @return the value of public.cn_stock_info.list_date
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public Date getListDate() {
        return listDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.list_date
     *
     * @param listDate the value for public.cn_stock_info.list_date
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setListDate(Date listDate) {
        this.listDate = listDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_info.create_date
     *
     * @return the value of public.cn_stock_info.create_date
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_info.create_date
     *
     * @param createDate the value for public.cn_stock_info.create_date
     *
     * @mbg.generated Mon Feb 27 12:20:02 CST 2023
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}