package com.tao.trade.infra.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class CnStockDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.id
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.symbol
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.name
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.close_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal closePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.open_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal openPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.low_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal lowPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.high_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal highPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.pre_close
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal preClose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.change
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal change;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.pct_chg
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal pctChg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.vol
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal vol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.amount
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.profit
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private BigDecimal profit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_daily.trade_date
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    private Date tradeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.id
     *
     * @return the value of public.cn_stock_daily.id
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.id
     *
     * @param id the value for public.cn_stock_daily.id
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.symbol
     *
     * @return the value of public.cn_stock_daily.symbol
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.symbol
     *
     * @param symbol the value for public.cn_stock_daily.symbol
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.name
     *
     * @return the value of public.cn_stock_daily.name
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.name
     *
     * @param name the value for public.cn_stock_daily.name
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.close_price
     *
     * @return the value of public.cn_stock_daily.close_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.close_price
     *
     * @param closePrice the value for public.cn_stock_daily.close_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setClosePrice(BigDecimal closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.open_price
     *
     * @return the value of public.cn_stock_daily.open_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.open_price
     *
     * @param openPrice the value for public.cn_stock_daily.open_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setOpenPrice(BigDecimal openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.low_price
     *
     * @return the value of public.cn_stock_daily.low_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.low_price
     *
     * @param lowPrice the value for public.cn_stock_daily.low_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setLowPrice(BigDecimal lowPrice) {
        this.lowPrice = lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.high_price
     *
     * @return the value of public.cn_stock_daily.high_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getHighPrice() {
        return highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.high_price
     *
     * @param highPrice the value for public.cn_stock_daily.high_price
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setHighPrice(BigDecimal highPrice) {
        this.highPrice = highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.pre_close
     *
     * @return the value of public.cn_stock_daily.pre_close
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getPreClose() {
        return preClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.pre_close
     *
     * @param preClose the value for public.cn_stock_daily.pre_close
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setPreClose(BigDecimal preClose) {
        this.preClose = preClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.change
     *
     * @return the value of public.cn_stock_daily.change
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getChange() {
        return change;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.change
     *
     * @param change the value for public.cn_stock_daily.change
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setChange(BigDecimal change) {
        this.change = change;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.pct_chg
     *
     * @return the value of public.cn_stock_daily.pct_chg
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getPctChg() {
        return pctChg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.pct_chg
     *
     * @param pctChg the value for public.cn_stock_daily.pct_chg
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setPctChg(BigDecimal pctChg) {
        this.pctChg = pctChg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.vol
     *
     * @return the value of public.cn_stock_daily.vol
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.vol
     *
     * @param vol the value for public.cn_stock_daily.vol
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setVol(BigDecimal vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.amount
     *
     * @return the value of public.cn_stock_daily.amount
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.amount
     *
     * @param amount the value for public.cn_stock_daily.amount
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.profit
     *
     * @return the value of public.cn_stock_daily.profit
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.profit
     *
     * @param profit the value for public.cn_stock_daily.profit
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_daily.trade_date
     *
     * @return the value of public.cn_stock_daily.trade_date
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public Date getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_daily.trade_date
     *
     * @param tradeDate the value for public.cn_stock_daily.trade_date
     *
     * @mbg.generated Thu Feb 23 21:22:50 CST 2023
     */
    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }
}