package com.tao.trade.infra.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class CnStockIpo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.id
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.symbol
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.name
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.ipo_date
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private Date ipoDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.issue_date
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private Date issueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.market_amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private BigDecimal marketAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.price
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.pe
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private BigDecimal pe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.limit_amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private BigDecimal limitAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.funds
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private BigDecimal funds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cn_stock_ipo.ballot
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    private BigDecimal ballot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.id
     *
     * @return the value of public.cn_stock_ipo.id
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.id
     *
     * @param id the value for public.cn_stock_ipo.id
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.symbol
     *
     * @return the value of public.cn_stock_ipo.symbol
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.symbol
     *
     * @param symbol the value for public.cn_stock_ipo.symbol
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.name
     *
     * @return the value of public.cn_stock_ipo.name
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.name
     *
     * @param name the value for public.cn_stock_ipo.name
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.ipo_date
     *
     * @return the value of public.cn_stock_ipo.ipo_date
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public Date getIpoDate() {
        return ipoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.ipo_date
     *
     * @param ipoDate the value for public.cn_stock_ipo.ipo_date
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setIpoDate(Date ipoDate) {
        this.ipoDate = ipoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.issue_date
     *
     * @return the value of public.cn_stock_ipo.issue_date
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public Date getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.issue_date
     *
     * @param issueDate the value for public.cn_stock_ipo.issue_date
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.amount
     *
     * @return the value of public.cn_stock_ipo.amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.amount
     *
     * @param amount the value for public.cn_stock_ipo.amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.market_amount
     *
     * @return the value of public.cn_stock_ipo.market_amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public BigDecimal getMarketAmount() {
        return marketAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.market_amount
     *
     * @param marketAmount the value for public.cn_stock_ipo.market_amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setMarketAmount(BigDecimal marketAmount) {
        this.marketAmount = marketAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.price
     *
     * @return the value of public.cn_stock_ipo.price
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.price
     *
     * @param price the value for public.cn_stock_ipo.price
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.pe
     *
     * @return the value of public.cn_stock_ipo.pe
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public BigDecimal getPe() {
        return pe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.pe
     *
     * @param pe the value for public.cn_stock_ipo.pe
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setPe(BigDecimal pe) {
        this.pe = pe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.limit_amount
     *
     * @return the value of public.cn_stock_ipo.limit_amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public BigDecimal getLimitAmount() {
        return limitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.limit_amount
     *
     * @param limitAmount the value for public.cn_stock_ipo.limit_amount
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setLimitAmount(BigDecimal limitAmount) {
        this.limitAmount = limitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.funds
     *
     * @return the value of public.cn_stock_ipo.funds
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public BigDecimal getFunds() {
        return funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.funds
     *
     * @param funds the value for public.cn_stock_ipo.funds
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setFunds(BigDecimal funds) {
        this.funds = funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cn_stock_ipo.ballot
     *
     * @return the value of public.cn_stock_ipo.ballot
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public BigDecimal getBallot() {
        return ballot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cn_stock_ipo.ballot
     *
     * @param ballot the value for public.cn_stock_ipo.ballot
     *
     * @mbg.generated Fri Feb 24 13:48:08 CST 2023
     */
    public void setBallot(BigDecimal ballot) {
        this.ballot = ballot;
    }
}