package com.tao.trade.infra.db.model;

import java.util.Date;

public class DataDeltaDate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.data_delta_date.name
     *
     * @mbg.generated Mon Feb 27 17:52:39 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.data_delta_date.data_date
     *
     * @mbg.generated Mon Feb 27 17:52:39 CST 2023
     */
    private Date dataDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.data_delta_date.name
     *
     * @return the value of public.data_delta_date.name
     *
     * @mbg.generated Mon Feb 27 17:52:39 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.data_delta_date.name
     *
     * @param name the value for public.data_delta_date.name
     *
     * @mbg.generated Mon Feb 27 17:52:39 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.data_delta_date.data_date
     *
     * @return the value of public.data_delta_date.data_date
     *
     * @mbg.generated Mon Feb 27 17:52:39 CST 2023
     */
    public Date getDataDate() {
        return dataDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.data_delta_date.data_date
     *
     * @param dataDate the value for public.data_delta_date.data_date
     *
     * @mbg.generated Mon Feb 27 17:52:39 CST 2023
     */
    public void setDataDate(Date dataDate) {
        this.dataDate = dataDate;
    }
}