package com.tao.trade.infra.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class QuaintFind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_find.id
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_find.symbol
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_find.status
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_find.trade_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private Date tradeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_find.close_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private BigDecimal closePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_find.strategy
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private String strategy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_find.id
     *
     * @return the value of public.quaint_find.id
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_find.id
     *
     * @param id the value for public.quaint_find.id
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_find.symbol
     *
     * @return the value of public.quaint_find.symbol
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_find.symbol
     *
     * @param symbol the value for public.quaint_find.symbol
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_find.status
     *
     * @return the value of public.quaint_find.status
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_find.status
     *
     * @param status the value for public.quaint_find.status
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_find.trade_date
     *
     * @return the value of public.quaint_find.trade_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public Date getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_find.trade_date
     *
     * @param tradeDate the value for public.quaint_find.trade_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_find.close_price
     *
     * @return the value of public.quaint_find.close_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public BigDecimal getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_find.close_price
     *
     * @param closePrice the value for public.quaint_find.close_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setClosePrice(BigDecimal closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_find.strategy
     *
     * @return the value of public.quaint_find.strategy
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public String getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_find.strategy
     *
     * @param strategy the value for public.quaint_find.strategy
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setStrategy(String strategy) {
        this.strategy = strategy;
    }
}