package com.tao.trade.infra.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class QuaintTrading {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.id
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.status
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.symbol
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.buy_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private Date buyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.sell_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private Date sellDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.alert_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private BigDecimal alertPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.buy_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private BigDecimal buyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.sell_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private BigDecimal sellPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.quaint_trading.strategy
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    private String strategy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.id
     *
     * @return the value of public.quaint_trading.id
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.id
     *
     * @param id the value for public.quaint_trading.id
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.status
     *
     * @return the value of public.quaint_trading.status
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.status
     *
     * @param status the value for public.quaint_trading.status
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.symbol
     *
     * @return the value of public.quaint_trading.symbol
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.symbol
     *
     * @param symbol the value for public.quaint_trading.symbol
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.buy_date
     *
     * @return the value of public.quaint_trading.buy_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.buy_date
     *
     * @param buyDate the value for public.quaint_trading.buy_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.sell_date
     *
     * @return the value of public.quaint_trading.sell_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public Date getSellDate() {
        return sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.sell_date
     *
     * @param sellDate the value for public.quaint_trading.sell_date
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setSellDate(Date sellDate) {
        this.sellDate = sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.alert_price
     *
     * @return the value of public.quaint_trading.alert_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public BigDecimal getAlertPrice() {
        return alertPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.alert_price
     *
     * @param alertPrice the value for public.quaint_trading.alert_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setAlertPrice(BigDecimal alertPrice) {
        this.alertPrice = alertPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.buy_price
     *
     * @return the value of public.quaint_trading.buy_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.buy_price
     *
     * @param buyPrice the value for public.quaint_trading.buy_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.sell_price
     *
     * @return the value of public.quaint_trading.sell_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.sell_price
     *
     * @param sellPrice the value for public.quaint_trading.sell_price
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.quaint_trading.strategy
     *
     * @return the value of public.quaint_trading.strategy
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public String getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.quaint_trading.strategy
     *
     * @param strategy the value for public.quaint_trading.strategy
     *
     * @mbg.generated Thu Mar 16 21:07:55 CST 2023
     */
    public void setStrategy(String strategy) {
        this.strategy = strategy;
    }
}