package com.tao.trade.infra.db.model;

public class SysStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_status.name
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.sys_status.status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_status.name
     *
     * @return the value of public.sys_status.name
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_status.name
     *
     * @param name the value for public.sys_status.name
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.sys_status.status
     *
     * @return the value of public.sys_status.status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.sys_status.status
     *
     * @param status the value for public.sys_status.status
     *
     * @mbg.generated Sun Feb 26 18:01:41 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }
}